main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from main import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('nuarte.urls', namespace='nuarte')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nuarte/urls.py
from django.urls import path
from nuarte.views import (
    index, ListarInstrumentosView, CadastrarInstrumentoView, AtualizarInstrumentoView, DeletarInstrumentoView, InstrumentoDetailView,
    ListarPerfisView, CadastrarPerfilView, AtualizarPerfilView, DeletarPerfilView,
    ListarHistoricoView, solicitar_instrumento, devolver_instrumento, administracao, listar_solicitacoes, aprovar_solicitacao, rejeitar_solicitacao, gerenciamento_instrumentos
)

app_name = 'nuarte'

urlpatterns = [
    path('', index, name='index'),
    path('listar_instrumentos/', ListarInstrumentosView.as_view(), name='listar_instrumentos'),
    path('cadastrar_instrumento/', CadastrarInstrumentoView.as_view(), name='cadastrar_instrumento'),
    path('atualizar_instrumento/<int:pk>/', AtualizarInstrumentoView.as_view(), name='atualizar_instrumento'),
    path('deletar_instrumento/<int:pk>/', DeletarInstrumentoView.as_view(), name='deletar_instrumento'),
    path('detalhes_instrumento/<int:pk>/', InstrumentoDetailView.as_view(), name='detalhes_instrumento'),

    path('listar_perfis/', ListarPerfisView.as_view(), name='listar_perfis'),
    path('cadastrar_perfil/', CadastrarPerfilView.as_view(), name='cadastrar_perfil'),
    path('atualizar_perfil/<int:pk>/', AtualizarPerfilView.as_view(), name='atualizar_perfil'),
    path('deletar_perfil/<int:pk>/', DeletarPerfilView.as_view(), name='deletar_perfil'),

    path('listar_historico/', ListarHistoricoView.as_view(), name='listar_historico'),
    path('solicitar_instrumento/', solicitar_instrumento, name='solicitar_instrumento'),
    path('devolver_instrumento/<int:instrumento_id>/', devolver_instrumento, name='devolver_instrumento'),
    path('listar_solicitacoes/', listar_solicitacoes, name='listar_solicitacoes'),
    path('aprovar_solicitacao/<int:historico_id>/', aprovar_solicitacao, name='aprovar_solicitacao'),
    path('rejeitar_solicitacao/<int:historico_id>/', rejeitar_solicitacao, name='rejeitar_solicitacao'),
    path('administracao/', administracao, name='administracao'),
    path('gerenciamento_instrumentos/', gerenciamento_instrumentos, name='gerenciamento_instrumentos'),
]

nuarte/models.py
from django.db import models
from django.contrib.auth.models import User


class Historico(models.Model):
    OPERACAO_CHOICES = [
        ('S', 'Solicitação de instrumento'),
        ('D', 'Devolução de instrumento'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    instrumento = models.ForeignKey('Instrumento', on_delete=models.CASCADE)
    operacao = models.CharField(max_length=1, choices=OPERACAO_CHOICES)
    data_operacao = models.DateTimeField(auto_now_add=True)
    devolucao = models.DateTimeField(null=True, blank=True)
    
    # Adicione o campo aprovado
    aprovado = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.usuario.username} - {self.instrumento.nome}"

class Instrumento(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    disponivel = models.BooleanField(default=True)
    imagem = models.ImageField(upload_to='instrumentos/', null=True, blank=True)

    def __str__(self):
        return self.nome


class Perfil(models.Model):
    USUARIO_CHOICES = [
        ('ADM', 'Administrador'),
        ('PROF', 'Professor'),
        ('ALUNO', 'Aluno'),
    ]

    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    tipo_usuario = models.CharField(max_length=5, choices=USUARIO_CHOICES)

    def __str__(self):
        return f"{self.usuario.username} - {self.tipo_usuario}"


    

    
    

nuarte/forms.py
from django import forms
from .models import Instrumento, Historico, Perfil

class InstrumentoForm(forms.ModelForm):
    class Meta:
        model = Instrumento
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['disponivel'].widget.attrs['class'] = 'form-check-input'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class HistoricoForm(forms.ModelForm):
    class Meta:
        model = Historico
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

nuarte/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from .models import Instrumento, Historico, Perfil
from .forms import InstrumentoForm, PerfilForm
from django.contrib.auth.decorators import user_passes_test, login_required
from django.utils.decorators import method_decorator

# Função de teste para verificar se o usuário é um administrador
def is_admin(user):
    return user.is_authenticated and user.groups.filter(name='Administradores').exists()

def admin_group_required(view_func):
    actual_decorator = user_passes_test(is_admin)
    if view_func:
        return actual_decorator(view_func)
    return actual_decorator

# Seção do decorador admin_group_required
def admin_group_required(view_func):
    actual_decorator = user_passes_test(is_admin)
    def _wrapped_view(request, *args, **kwargs):
        if request.user.groups.filter(name='Administradores').exists():
            return view_func(request, *args, **kwargs)
        else:
            return render(request, '403.html') 
    return _wrapped_view

# Seção do decorador admin_group_required
def admin_group_required(view_func):
    actual_decorator = user_passes_test(is_admin)
    def _wrapped_view(request, *args, **kwargs):
        if request.user.groups.filter(name='Administradores').exists():
            return view_func(request, *args, **kwargs)
        else:
            return render(request, '403.html') 
    return _wrapped_view

class ListarInstrumentosView(ListView):
    model = Instrumento
    template_name = 'nuarte/listar_instrumentos.html'
    context_object_name = 'instrumentos'
    paginate_by = 6

@method_decorator(user_passes_test(is_admin), name='dispatch')
class CadastrarInstrumentoView(SuccessMessageMixin, CreateView):
    model = Instrumento
    form_class = InstrumentoForm
    template_name = 'nuarte/cadastrar_instrumento.html'
    success_url = reverse_lazy('nuarte:listar_instrumentos')
    success_message = 'Instrumento cadastrado com sucesso!'

@method_decorator(user_passes_test(is_admin), name='dispatch')
class AtualizarInstrumentoView(SuccessMessageMixin, UpdateView):
    model = Instrumento
    form_class = InstrumentoForm
    template_name = 'nuarte/editar_instrumento.html'
    success_url = reverse_lazy('nuarte:listar_instrumentos')
    success_message = 'Instrumento atualizado com sucesso!'

@method_decorator(user_passes_test(is_admin), name='dispatch')
class DeletarInstrumentoView(SuccessMessageMixin, DeleteView):
    model = Instrumento
    template_name = 'nuarte/deletar_instrumento.html'
    success_url = reverse_lazy('nuarte:listar_instrumentos')
    success_message = 'Instrumento deletado com sucesso!'

class ListarPerfisView(ListView):
    model = Perfil
    template_name = 'nuarte/listar_perfis.html'
    context_object_name = 'perfis'

class CadastrarPerfilView(SuccessMessageMixin, CreateView):
    model = Perfil
    form_class = PerfilForm
    template_name = 'nuarte/cadastrar_perfil.html'
    success_url = reverse_lazy('nuarte:listar_perfis')
    success_message = 'Perfil cadastrado com sucesso!'


class AtualizarPerfilView(SuccessMessageMixin, UpdateView):
    model = Perfil
    form_class = PerfilForm
    template_name = 'nuarte/atualizar_perfil.html'
    success_url = reverse_lazy('nuarte:listar_perfis')
    success_message = 'Perfil atualizado com sucesso!'

class DeletarPerfilView(SuccessMessageMixin, DeleteView):
    model = Perfil
    template_name = 'nuarte/deletar_perfil.html'
    success_url = reverse_lazy('nuarte:listar_perfis')
    success_message = 'Perfil deletado com sucesso!'

class ListarHistoricoView(ListView):
    template_name = 'nuarte/listar_historico.html'

    def get(self, request, *args, **kwargs):
        historico = Historico.objects.all()
        return render(request, self.template_name, {'historico': historico})

    paginate_by = 8

class InstrumentoDetailView(DetailView):
    model = Instrumento
    template_name = 'nuarte/detalhes_instrumento.html'
    context_object_name = 'instrumento'

from django.shortcuts import render, redirect
from .models import Instrumento, Historico

def solicitar_instrumento(request):
    if request.method == 'POST':
        instrumento_id = request.POST.get('instrumento')
        instrumento = Instrumento.objects.get(pk=instrumento_id)

        Historico.objects.create(
            usuario=request.user,
            instrumento=instrumento,
            operacao='Solicitação de instrumento'
        )
 
        messages.success(request, 'Instrumento solicitado com sucesso!')
        return redirect('nuarte:listar_instrumentos')

    instrumentos_disponiveis = Instrumento.objects.filter(disponivel=True)
    return render(request, 'nuarte/solicitar_instrumento.html', {'instrumentos_disponiveis': instrumentos_disponiveis})

def devolver_instrumento(request, instrumento_id):
    try:
        instrumento = Instrumento.objects.get(pk=instrumento_id)

        if not instrumento.disponivel:
            instrumento.disponivel = True
            instrumento.save()

            Historico.objects.create(
                usuario=request.user,
                instrumento=instrumento,
                operacao='Devolução de instrumento'
            )

            messages.success(request, 'Instrumento devolvido com sucesso!')
        else:
            messages.error(request, 'Este instrumento já está disponível.')

        return redirect('nuarte:listar_instrumentos')

    except Instrumento.DoesNotExist:
        messages.error(request, 'Instrumento não encontrado.')
        return redirect('nuarte:listar_instrumentos')

def listar_solicitacoes(request):
    # Obtém todas as solicitações pendentes
    solicitacoes_pendentes = Historico.objects.filter(aprovado=False)

    return render(request, 'nuarte/listar_solicitacoes.html', {'solicitacoes_pendentes': solicitacoes_pendentes})

def aprovar_solicitacao(request, historico_id):
    historico = get_object_or_404(Historico, pk=historico_id)

    # Atualiza o status para aprovado e a disponibilidade do instrumento
    historico.aprovado = True
    historico.instrumento.disponivel = False  # Instrumento indisponível após aprovação
    historico.save()
    historico.instrumento.save()

    messages.success(request, 'Solicitação aprovada com sucesso!')
    return redirect('nuarte:listar_solicitacoes')

def rejeitar_solicitacao(request, historico_id):
    historico = get_object_or_404(Historico, pk=historico_id)

    # Atualiza o status para rejeitado
    historico.aprovado = False
    historico.save()

    messages.success(request, 'Solicitação rejeitada com sucesso!')
    return redirect('nuarte:listar_solicitacoes')

@admin_group_required
def administracao(request):
    return render(request, 'nuarte/administracao.html')

def index(request):
    return render(request, 'nuarte/index.html')

def gerenciamento_instrumentos(request):
    instrumentos = Instrumento.objects.all()
    return render(request, 'nuarte/gerenciamento_instrumentos.html', {'instrumentos': instrumentos})

nuarte/templates/nuarte/atualizar_perfil.html
{% extends 'base.html' %}

{% block title %}Atualizar Perfil{% endblock %}

{% block content %}
    <h1>Atualizar Perfil</h1>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
    
    <a href="{% url 'nuarte:listar_perfis' %}" class="btn btn-secondary mt-3">Voltar para a lista de perfis</a>
{% endblock %}

nuarte/templates/nuarte/cadastrar_instrumento.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Cadastrar Novo Instrumento</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.nome.id_for_label }}">Nome do Instrumento:</label>
        {{ form.nome }}
      </div>
      <div class="form-group">
        <label for="{{ form.descricao.id_for_label }}">Descrição:</label>
        {{ form.descricao }}
      </div>
      <div class="form-group">
        <label for="{{ form.imagem.id_for_label }}">Imagem:</label>
        {{ form.imagem }}
      </div>
      <div class="form-group form-check">
        {{ form.disponivel }}
        <label class="form-check-label" for="{{ form.disponivel.id_for_label }}">Disponível</label>
      </div>
      <button type="submit" class="btn btn-primary">Cadastrar Instrumento</button>
    </form>
    <br>
    <a href="{% url 'nuarte:listar_instrumentos' %}" class="btn btn-secondary">Voltar para a Listagem</a>
  </div>
{% endblock %}

nuarte/templates/nuarte/cadastrar_perfil.html
{% extends 'base.html' %}


{% block title %}Cadastrar Perfil{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>Cadastrar Perfil</h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>

        <a href="{% url 'nuarte:listar_perfis' %}" class="btn btn-secondary mt-3">Voltar para a lista de perfis</a>
    </div>
{% endblock %}

nuarte/templates/nuarte/deletar_instrumento.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h2 class="my-4">Deletar Instrumento</h2>
    <p>Você tem certeza que deseja deletar o instrumento "{{ instrumento.nome }}"?</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Sim, deletar</button>
    </form>
  </div>
{% endblock %}

nuarte/templates/nuarte/deletar_perfil.html
{% extends 'base.html' %}

{% block title %}Deletar Perfil{% endblock %}

{% block content %}
    <h1>Deletar Perfil</h1>
    
    <p>Tem certeza que deseja deletar o perfil de {{ perfil.usuario.username }}?</p>
    
    <form method="post">
        {% csrf_token %}
        
        <button type="submit" class="btn btn-danger">Deletar</button>
    </form>
    
    <a href="{% url 'nuarte:listar_perfis' %}" class="btn btn-secondary mt-3">Cancelar</a>
{% endblock %}

nuarte/templates/nuarte/detalhes_instrumento.html
{% extends 'base.html' %}

{% block title %}Detalhes do Instrumento{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h1 class="mb-4">Detalhes do Instrumento</h1>
    <div class="instrumento-details">
      <p><strong>Nome:</strong> {{ instrumento.nome }}</p>
      <p><strong>Descrição:</strong> {{ instrumento.descricao }}</p>
      <p><strong>Disponível:</strong> {% if instrumento.disponivel %}Sim{% else %}Não{% endif %}</p>

      {% if instrumento.imagem %}
        <div class="instrumento-image">
          <img src="{{ instrumento.imagem.url }}" alt="{{ instrumento.nome }}" class="img-fluid rounded">
        </div>
      {% endif %}

      <div class="mt-4">
        <a href="{% url 'nuarte:listar_instrumentos' %}" class="btn btn-secondary mr-2">Voltar para a Lista de Instrumentos</a>
        <a href="{% url 'nuarte:solicitar_instrumento' %}" class="btn btn-primary mr-2">Solicitar Instrumento</a>
        <a href="{% url 'nuarte:devolver_instrumento' instrumento.id %}" class="btn btn-warning mr-2">Devolver Instrumento</a>
      </div>
    </div>

    {% if messages %}
      <div class="mt-4">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>

  <style>
    .container {
      max-width: 100%;
    }

    .instrumento-details {
      background-color: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .instrumento-image {
      width: 200px;
      height: 200px;
      overflow: hidden;
      border-radius: 8px;
      margin-top: 15px;
    }

    img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .btn {
      margin-top: 15px;
    }
  </style>
{% endblock %}

nuarte/templates/nuarte/gerenciamento_instrumentos.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <h2>Gerenciar Instrumentos</h2>

  <!-- Botão para cadastrar novo instrumento -->
  <a href="{% url 'nuarte:cadastrar_instrumento' %}" class="btn btn-primary mb-3">Cadastrar Novo Instrumento</a>

  <!-- Tabela de instrumentos -->
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome do Instrumento</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for instrumento in instrumentos %}
      <tr>
        <td>{{ instrumento.nome }}</td>
        <td>
          <a href="{% url 'nuarte:detalhes_instrumento' instrumento.id %}" class="btn btn-info btn-sm">Detalhes</a>
          <a href="{% url 'nuarte:atualizar_instrumento' instrumento.id %}" class="btn btn-info btn-sm">Atualizar</a>
          <a href="{% url 'nuarte:deletar_instrumento' instrumento.id %}" class="btn btn-danger btn-sm">Deletar</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

nuarte/templates/nuarte/listar_instrumentos.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    {% if messages %}
    <div class="container mt-4">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    </div>
  {% endif %}
    <h2 class="my-4">Lista de Instrumentos</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nome do Instrumento</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for instrumento in instrumentos %}
          <tr>
            <td>{{ instrumento.nome }}</td>
            <td>
              <a class="btn btn-info" href="{% url 'nuarte:detalhes_instrumento' instrumento.id %}">Detalhes</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <nav aria-label="Page navigation example" style="margin-top: 40px;">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Primeira">
              <span aria-hidden="true">&laquo;&laquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
          <li class="page-item{% if num == page_obj.number %} active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próxima">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
              <span aria-hidden="true">&raquo;&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>

  <style>
    /* Adicione estilos personalizados aqui */
    .container {
      max-width: 100%;
    }

    table {
      width: 100%;
      margin-bottom: 20px;
    }

    th, td {
      padding: 10px;
      text-align: left;
    }

    th {
      background-color: #007bff;
      color: #fff;
    }

    tbody tr:nth-child(even) {
      background-color: #f8f9fa;
    }

    .pagination {
      margin-top: 20px;
    }

    .pagination li {
      display: inline-block;
      margin-right: 5px;
    }

    .pagination li.active a {
      background-color: #007bff;
      border-color: #007bff;
    }

    .pagination li a {
      color: #007bff;
    }

    .alert {
      margin-top: 20px;
    }
  </style>
{% endblock %}

nuarte/templates/nuarte/listar_perfis.html
{% extends 'base.html' %}

{% block title %}Listar Perfis{% endblock %}

{% block content %}
    <h1>Listar Perfis</h1>

    {% if perfis %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Usuário</th>
                    <th scope="col">Tipo de Usuário</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for perfil in perfis %}
                    <tr>
                        <td>{{ perfil.usuario.username }}</td>
                        <td>{{ perfil.tipo_usuario }}</td>
                        <td>
                            <a href="{% url 'nuarte:atualizar_perfil' perfil.id %}" class="btn btn-info">Atualizar</a>
                            <a href="{% url 'nuarte:deletar_perfil' perfil.id %}" class="btn btn-danger">Deletar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Nenhum perfil encontrado.</p>
    {% endif %}

    <a href="{% url 'nuarte:cadastrar_perfil' %}" class="btn btn-success">Cadastrar Novo Perfil</a>

    {% if messages %}
  <div class="container mt-4">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  </div>
{% endif %}

{% endblock %}

nuarte/templates/nuarte/listar_solicitacoes.html
{% extends 'base.html' %}

{% block title %}Listar Solicitações{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h1 class="my-4">Listar Solicitações Pendentes</h1>

        {% if solicitacoes_pendentes %}
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Usuário:</th>
                            <th>Instrumento:</th>
                            <th>Justificvativa:</th>
                            <th>Ação:</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for solicitacao in solicitacoes_pendentes %}
                            <tr>
                                <td>{{ solicitacao.usuario.username }}</td>
                                <td>{{ solicitacao.instrumento.nome }}</td>
                                <td>{{ solicitacao.data_solicitacao }}</td>
                                <td>
                                    <a href="{% url 'nuarte:aprovar_solicitacao' solicitacao.id %}" class="btn btn-success">Aprovar</a>
                                    <a href="{% url 'nuarte:rejeitar_solicitacao' solicitacao.id %}" class="btn btn-danger">Rejeitar</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p>Não há solicitações pendentes.</p>
        {% endif %}
    </div>

    <nav aria-label="Page navigation example" class="pagination-container mt-4">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Primeira">
              <span aria-hidden="true">&laquo;&laquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Anterior">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% endif %}
          {% for num in page_obj.paginator.page_range %}
          <li class="page-item{% if num == page_obj.number %} active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Próxima">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Última">
              <span aria-hidden="true">&raquo;&raquo;</span>
            </a>
          </li>
          {% endif %}
        </ul>
    </nav>

    {% if messages %}
        <div class="container mt-4">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

nuarte/templates/nuarte/solicitar_instrumento.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h2 class="my-4">Solicitar Instrumento</h2>
    <form method="post" action="{% url 'nuarte:solicitar_instrumento' %}">
      {% csrf_token %}
      <input type="hidden" name="usuario" value="{{ user.id }}">
      <div class="form-group">
        <label for="perfil">Selecione o Perfil:</label>
        <select name="perfil" class="form-control" required>
          <option value="ALUNO">Aluno</option>
          <option value="PROFESSOR">Professor</option>
        </select>
      </div>
      <div class="form-group">
        <label for="instrumento">Selecione o Instrumento:</label>
        <select name="instrumento" class="form-control" required>
          {% for instrumento in instrumentos_disponiveis %}
            <option value="{{ instrumento.id }}">{{ instrumento.nome }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="data_solicitacao">Data de Solicitação:</label>
        <input type="date" name="data_solicitacao" class="form-control" required>
      </div>
      <button type="submit" class="btn btn-primary">Solicitar Instrumento</button>
    </form>
  </div>
{% endblock %}